version: '3'

services:
  vnc-server:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - VNC_PASSWORD=${VNC_PASSWORD}
    image: javimosch/vncsrv
    container_name: vnc-server
    expose:
      - "5900"
    volumes:
      - ./data:/data
    environment:
      - DISPLAY=:0
    shm_size: 256m

  novnc:
    image: bonigarcia/novnc:1.1.0
    container_name: novnc
    expose:
      - "6080"
    environment:
      - AUTOCONNECT=true
      - VNC_SERVER=vnc-server:5900
      - VIEW_ONLY=false
    env_file:
      .env
    depends_on:
      - vnc-server

  auth-proxy:
    image: nginx:alpine
    ports:
      - "6080:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./.htpasswd:/etc/nginx/.htpasswd:ro
    depends_on:
      - novnc

networks:
  default:
    name: vnc-network